# Generated by Django 6.1 on 2026-08-27 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('ubicacion', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('principal', 'Principal'), ('sucursal', 'Sucursal')], max_length=20)),
                ('capacidad', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Bodegas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('ciudad', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('venue', 'Venue'), ('estudio', 'Estudio')], max_length=20)),
                ('email_contacto', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('pais', models.CharField(max_length=100)),
                ('email_contacto', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=30)),
                ('tasa_puntualidad', models.DecimalField(decimal_places=1, max_digits=4)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('categoria', models.CharField(choices=[('instrumento', 'Instrumento'), ('sonido', 'Sonido'), ('iluminacion', 'Iluminación')], max_length=20)),
                ('peso_kg', models.DecimalField(decimal_places=1, max_digits=7)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='courier.proveedor')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('destino', models.CharField(max_length=200)),
                ('peso_total_kg', models.DecimalField(decimal_places=1, max_digits=7)),
                ('estado', models.CharField(choices=[('preparando', 'Preparando'), ('en_transito', 'En tránsito'), ('en_aduana', 'En aduana'), ('entregado', 'Entregado')], default='preparando', max_length=20)),
                ('fecha_envio', models.DateField()),
                ('fecha_estimada_entrega', models.DateField()),
                ('fecha_real_entrega', models.DateField(blank=True, null=True)),
                ('ubicacion_actual', models.CharField(max_length=200)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios', to='courier.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios', to='courier.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios', to='courier.proveedor')),
            ],
            options={
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=200)),
                ('fecha_hora', models.DateTimeField()),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='courier.envio')),
            ],
            options={
                'verbose_name': 'Evento de seguimiento',
                'verbose_name_plural': 'Eventos de seguimiento',
                'ordering': ['fecha_hora'],
            },
        ),
    ]
