# Generated by Django 6.1 on 2026-09-06 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='ubicacion',
            field=models.CharField(max_length=150, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email_contacto',
            field=models.EmailField(max_length=254, verbose_name='Correo de contacto'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=30, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='codigo',
            field=models.CharField(max_length=30, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='fecha_envio',
            field=models.DateField(verbose_name='Fecha de envío'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='fecha_estimada_entrega',
            field=models.DateField(verbose_name='Fecha estimada de entrega'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='fecha_real_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha real de entrega'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='peso_total_kg',
            field=models.DecimalField(decimal_places=1, max_digits=7, verbose_name='Peso total (kg)'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='ubicacion_actual',
            field=models.CharField(max_length=200, verbose_name='Ubicación actual'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='peso_kg',
            field=models.DecimalField(decimal_places=1, max_digits=7, verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email_contacto',
            field=models.EmailField(max_length=254, verbose_name='Correo de contacto'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='pais',
            field=models.CharField(max_length=100, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tasa_puntualidad',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Tasa de puntualidad (%)'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=30, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='seguimientoevento',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='seguimientoevento',
            name='fecha_hora',
            field=models.DateTimeField(verbose_name='Fecha y hora'),
        ),
        migrations.AlterField(
            model_name='seguimientoevento',
            name='ubicacion',
            field=models.CharField(max_length=200, verbose_name='Ubicación'),
        ),
    ]
