# Generated by Django 6.1 on 2026-10-03 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0002_alter_bodega_ubicacion_alter_cliente_email_contacto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('licencia', models.CharField(max_length=30, unique=True, verbose_name='Licencia')),
                ('telefono', models.CharField(max_length=30, verbose_name='Teléfono')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ComprobanteEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_receptor', models.CharField(max_length=150, verbose_name='Nombre del receptor')),
                ('firma_url', models.CharField(blank=True, max_length=300, verbose_name='Firma digital (URL/archivo)')),
                ('foto_url', models.CharField(blank=True, max_length=300, verbose_name='Foto de la mercadería (URL/archivo)')),
                ('codigo_escaneado', models.CharField(blank=True, max_length=100, verbose_name='Código QR/barras escaneado')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y hora de entrega')),
                ('envio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comprobante', to='courier.envio')),
            ],
            options={
                'verbose_name': 'Comprobante de entrega',
                'verbose_name_plural': 'Comprobantes de entrega',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.AddField(
            model_name='envio',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios', to='courier.conductor'),
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('retraso', 'Retraso'), ('desvio', 'Desvío'), ('falla_mecanica', 'Falla mecánica'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y hora')),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='courier.envio')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True, verbose_name='Patente')),
                ('tipo', models.CharField(choices=[('camion', 'Camión'), ('van', 'Van'), ('trailer', 'Tráiler')], max_length=20)),
                ('capacidad_kg', models.DecimalField(decimal_places=1, max_digits=8, verbose_name='Capacidad (kg)')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='courier.proveedor')),
            ],
            options={
                'ordering': ['patente'],
            },
        ),
        migrations.AddField(
            model_name='conductor',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conductores', to='courier.vehiculo'),
        ),
        migrations.AddField(
            model_name='envio',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios', to='courier.vehiculo'),
        ),
    ]
