# Generated by Django 6.1 on 2026-10-03 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0003_conductor_comprobanteentrega_envio_conductor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conductor',
            options={'ordering': ['nombre'], 'verbose_name': 'Conductor', 'verbose_name_plural': 'Conductores'},
        ),
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'ordering': ['patente'], 'verbose_name': 'Vehículo', 'verbose_name_plural': 'Vehículos'},
        ),
    ]
