# Generated by Django 6.1 on 2026-10-05 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0004_alter_conductor_options_alter_vehiculo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='envio',
            options={'ordering': ['-fecha_envio'], 'verbose_name': 'Envío', 'verbose_name_plural': 'Envíos'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['nombre'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
    ]
